version: '3'

services:
  # MySQL
  mysql:
    image: mysql:8.0.23
    container_name: pclcm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: zh76LUBx
      MYSQL_DATABASE: pclcm
      MYSQL_USER: user
      MYSQL_PASSWORD: JyCydsk8
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker-init/db/data:/var/lib/mysql
    - ./docker-init/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker-init/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    cap_add:
      - SYS_NICE

  # phpMyAdmin
  phpmyadmin:
    container_name: pclcm_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=pclcm_mysql
    - PMA_USER=root
    - PMA_PASSWORD=zh76LUBx
    ports:
    - 8081:80
