"""Modify ForeignKeys nullable=True

Revision ID: 0a8639b17f37
Revises: 647e4b1c5cc3
Create Date: 2023-01-05 08:55:34.257768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a8639b17f37'
down_revision = '647e4b1c5cc3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_account_base', 'base_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='拠点ID')
    op.alter_column('m_account_group', 'group_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='グループID')
    op.alter_column('m_account_role', 'role_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='ロールID')
    op.alter_column('m_role_operation', 'operation_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='オペレーションID')
    op.alter_column('t_asset', 'kitting_history_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='キッティング履歴ID')
    op.alter_column('t_disposal', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='資産ID')
    op.alter_column('t_notification_to', 'account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='アカウントID')
    op.alter_column('t_notification_to', 'group_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='グループID')
    op.alter_column('t_notification_to', 'base_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='拠点ID')
    op.alter_column('t_order', 'kitting_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='キッティングマスタID')
    op.alter_column('t_order', 'supplier_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='発注先ID')
    op.alter_column('t_pick_up', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='資産ID')
    op.alter_column('t_procurement', 'quotation_account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='見積担当者')
    op.alter_column('t_procurement', 'account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='承認者')
    op.alter_column('t_repairing', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='資産ID')
    op.alter_column('t_shipping', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='資産ID')
    op.alter_column('t_use', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='資産ID')
    op.alter_column('t_use', 'account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='アカウントID')
    op.alter_column('t_use', 'group_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='グループID')
    op.alter_column('t_use', 'base_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='拠点ID')
    op.alter_column('m_item_set', 'item_set_maker_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_use', 'base_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='拠点ID')
    op.alter_column('t_use', 'group_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='グループID')
    op.alter_column('t_use', 'account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='アカウントID')
    op.alter_column('t_use', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='資産ID')
    op.alter_column('t_shipping', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='資産ID')
    op.alter_column('t_repairing', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='資産ID')
    op.alter_column('t_procurement', 'account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='承認者')
    op.alter_column('t_procurement', 'quotation_account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='見積担当者')
    op.alter_column('t_pick_up', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='資産ID')
    op.alter_column('t_order', 'supplier_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='発注先ID')
    op.alter_column('t_order', 'kitting_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='キッティングマスタID')
    op.alter_column('t_order', 'item_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='品目ID')
    op.alter_column('t_order', 'procurement_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='調達ID')
    op.alter_column('t_notification_to', 'base_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='拠点ID')
    op.alter_column('t_notification_to', 'group_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='グループID')
    op.alter_column('t_notification_to', 'account_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='アカウントID')
    op.alter_column('t_disposal', 'asset_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='資産ID')
    op.alter_column('t_asset', 'kitting_history_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='キッティング履歴ID')
    op.alter_column('m_role_operation', 'operation_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='オペレーションID')
    op.alter_column('m_item_set_item', 'item_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='品目ID:セットされる個別の品目ID')
    op.alter_column('m_account_role', 'role_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='ロールID')
    op.alter_column('m_account_group', 'group_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='グループID')
    op.alter_column('m_account_base', 'base_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='拠点ID')
    # ### end Alembic commands ###
