"""Add columns hardware_confirm_account_id, software_confirm_account_id, kitting_confirm_account_id, functional_confirm_account_id, kitting_comment into table t_kitting

Revision ID: 0f34143e1a71
Revises: 1d23201cf514
Create Date: 2023-02-13 08:48:47.129169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f34143e1a71'
down_revision = '6f105b7b132f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_pick_up', sa.Column(
        'pick_up_type', sa.Integer(), nullable=True, comment='集荷区分: 0:集荷待ち（返却）1:集荷待ち（修理）'))
    op.add_column('t_kitting', sa.Column(
        'hardware_confirm_account_id', sa.Integer(), nullable=True))
    op.add_column('t_kitting', sa.Column(
        'software_confirm_account_id', sa.Integer(), nullable=True))
    op.add_column('t_kitting', sa.Column(
        'kitting_confirm_account_id', sa.Integer(), nullable=True))
    op.add_column('t_kitting', sa.Column(
        'functional_confirm_account_id', sa.Integer(), nullable=True))
    op.add_column('t_kitting', sa.Column(
        'kitting_comment', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 't_kitting', 'm_account', [
                          'software_confirm_account_id'], ['account_id'])
    op.create_foreign_key(None, 't_kitting', 'm_account', [
                          'hardware_confirm_account_id'], ['account_id'])
    op.create_foreign_key(None, 't_kitting', 'm_account', [
                          'kitting_confirm_account_id'], ['account_id'])
    op.create_foreign_key(None, 't_kitting', 'm_account', [
                          'functional_confirm_account_id'], ['account_id'])
    op.alter_column('t_pick_up', 'pick_up_arrangement_on',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_comment='集荷手配日',
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_pick_up', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('t_shipping', 'reception_on',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_comment='受付日',
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_shipping', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_shipping', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('t_shipping', 'reception_on',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_comment='受付日',
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('t_pick_up', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('t_pick_up', 'pick_up_arrangement_on',
                    existing_type=mysql.DATETIME(),
                    nullable=False,
                    existing_comment='集荷手配日',
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 't_kitting', type_='foreignkey')
    op.drop_constraint(None, 't_kitting', type_='foreignkey')
    op.drop_constraint(None, 't_kitting', type_='foreignkey')
    op.drop_constraint(None, 't_kitting', type_='foreignkey')
    op.drop_column('t_kitting', 'kitting_comment')
    op.drop_column('t_kitting', 'functional_confirm_account_id')
    op.drop_column('t_kitting', 'kitting_confirm_account_id')
    op.drop_column('t_kitting', 'software_confirm_account_id')
    op.drop_column('t_kitting', 'hardware_confirm_account_id')
    # ### end Alembic commands ###
