"""Create table t_asset_set_asset, t_asset_set 2023-02-03

Revision ID: 1d23201cf514
Revises: 96df6865a507
Create Date: 2023-02-03 15:52:01.660025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d23201cf514'
down_revision = '96df6865a507'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_asset_set',
                    sa.Column('asset_id_set', sa.Integer(), nullable=False),
                    sa.Column('asset_set_type', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('asset_set_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('asset_set_jan_code', sa.String(
                        length=13), nullable=True),
                    sa.Column('asset_set_maker_id',
                              sa.Integer(), nullable=False),
                    sa.Column('asset_set_maker_model', sa.String(
                        length=200), nullable=True),
                    sa.Column('asset_set_os', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('asset_set_expiration_date_from',
                              sa.Date(), nullable=True),
                    sa.Column('asset_set_expiration_date_to',
                              sa.Date(), nullable=True),
                    sa.Column('tax_inc_price', sa.Float(),
                              nullable=True, comment='税には価格が含まれます'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', sa.Integer(), nullable=True,
                              comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', sa.Integer(), nullable=True,
                              comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', sa.DateTime(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', sa.Integer(),
                              nullable=True, comment='削除者'),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(['asset_set_maker_id'], [
                        'm_maker.maker_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('asset_id_set')
                    )
    op.create_table('t_asset_set_asset',
                    sa.Column('asset_set_asset_id',
                              sa.Integer(), nullable=False),
                    sa.Column('asset_id_set', sa.Integer(), nullable=False),
                    sa.Column('asset_id', sa.Integer(),
                              nullable=True, comment='資産ID'),
                    sa.Column('is_main', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='メインフラグ:0：非メイン、1：メイン品目。「メイン可」の品目タイプの品目が対象'),
                    sa.Column('sort_order', sa.Integer(), server_default=sa.text(
                        '1'), nullable=False, comment='表示順'),
                    sa.Column('version', sa.Integer(), server_default=sa.text(
                        '1'), nullable=False, comment='バージョン:楽観的排他で利用'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', sa.Integer(), nullable=True,
                              comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', sa.Integer(), nullable=True,
                              comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', sa.DateTime(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', sa.Integer(),
                              nullable=True, comment='削除者'),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['asset_id_set'], ['t_asset_set.asset_id_set'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('asset_set_asset_id')
                    )
    op.drop_table('m_asset_set')
    op.drop_table('m_asset_set_asset')
    op.drop_column('t_procurement', 'quotation_requester')
    op.drop_column('t_procurement', 'approval_requester')
    op.add_column('t_procurement', sa.Column('quotation_requester',
                  sa.Integer(), nullable=True, comment='見積依頼者'))
    op.add_column('t_procurement', sa.Column('approval_requester',
                  sa.Integer(), nullable=True, comment='承認依頼者'))
    op.create_foreign_key(None, 't_procurement', 'm_account', [
                          'quotation_requester'], ['account_id'])
    op.create_foreign_key(None, 't_procurement', 'm_account', [
                          'approval_requester'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_procurement', type_='foreignkey')
    op.drop_constraint(None, 't_procurement', type_='foreignkey')
    op.create_table('m_asset_set_asset',
                    sa.Column('item_set_item_id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('item_id_set', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('item_id', mysql.INTEGER(), autoincrement=False,
                              nullable=False, comment='品目ID:セットされる個別の品目ID'),
                    sa.Column('is_main', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='メインフラグ:0：非メイン、1：メイン品目。「メイン可」の品目タイプの品目が対象'),
                    sa.Column('sort_order', mysql.INTEGER(), server_default=sa.text(
                        "'1'"), autoincrement=False, nullable=False, comment='表示順'),
                    sa.Column('version', mysql.INTEGER(), server_default=sa.text(
                        "'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
                    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', mysql.DATETIME(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', mysql.INTEGER(),
                              autoincrement=False, nullable=True, comment='削除者'),
                    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], name='m_asset_set_asset_ibfk_1'),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], name='m_asset_set_asset_ibfk_2'),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['m_item.item_id'], name='m_asset_set_asset_ibfk_3'),
                    sa.ForeignKeyConstraint(
                        ['item_id_set'], ['m_item_set.item_id_set'], name='m_asset_set_asset_ibfk_4'),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], name='m_asset_set_asset_ibfk_5'),
                    sa.PrimaryKeyConstraint('item_set_item_id'),
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('m_asset_set',
                    sa.Column('item_id_set', mysql.INTEGER(), autoincrement=True,
                              nullable=False, comment='セット用品目ID:セット用の品目の品目ID'),
                    sa.Column('item_set_type', mysql.INTEGER(), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False),
                    sa.Column('item_set_name', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=200), nullable=True),
                    sa.Column('item_set_jan_code', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=13), nullable=True),
                    sa.Column('item_set_maker_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('item_set_maker_model', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=200), nullable=True),
                    sa.Column('item_set_os', mysql.INTEGER(), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False),
                    sa.Column('item_set_expiration_date_from',
                              sa.DATE(), nullable=True),
                    sa.Column('item_set_expiration_date_to',
                              sa.DATE(), nullable=True),
                    sa.Column('tax_inc_price', mysql.FLOAT(),
                              nullable=True, comment='税には価格が含まれます'),
                    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', mysql.DATETIME(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', mysql.INTEGER(),
                              autoincrement=False, nullable=True, comment='削除者'),
                    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], name='m_asset_set_ibfk_1'),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], name='m_asset_set_ibfk_2'),
                    sa.ForeignKeyConstraint(['item_set_maker_id'], [
                        'm_maker.maker_id'], name='m_asset_set_ibfk_3'),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], name='m_asset_set_ibfk_4'),
                    sa.PrimaryKeyConstraint('item_id_set'),
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('t_asset_set_asset')
    op.drop_table('t_asset_set')
    # ### end Alembic commands ###
