"""Add foreignkey account_ table t_asset

Revision ID: 230b53d61f82
Revises: 1d23201cf514
Create Date: 2023-02-08 10:14:15.829757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230b53d61f82'
down_revision = '1d23201cf514'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_asset', sa.Column(
        'account_id', sa.Integer(), nullable=True, comment='資産ID'))
    op.create_foreign_key(None, 't_asset', 'm_account', [
                          'account_id'], ['account_id'])
    op.add_column('t_asset_set', sa.Column(
        'order_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_asset_set', 'order_id')
    op.drop_constraint(None, 't_asset', type_='foreignkey')
    op.drop_column('t_asset', 'account_id')
    # ### end Alembic commands ###
