"""Drop column kitting_master_id in table t_kitting, addcolumns kitting_master_id, depreciation_rule_id into t_order

Revision ID: 29b78adcf718
Revises: c5021be3d716
Create Date: 2023-02-22 15:20:01.391589

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b78adcf718'
down_revision = 'c5021be3d716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_asset', sa.Column('kitting_master_id',
                  sa.Integer(), nullable=True, comment='キッティングマスタID'))
    op.add_column('t_order', sa.Column(
        'depreciation_rule_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
