"""Add column item_id_set into table t_arrival 2023-01-19

Revision ID: 459b6436026e
Revises: 59aba2baa0eb
Create Date: 2023-01-19 10:15:00.429848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '459b6436026e'
down_revision = '59aba2baa0eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('t_arrival', sa.Column(
    #     'item_id_set', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 't_arrival', 'm_item_set', [
    #                       'item_id_set'], ['item_id_set'])
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('t_arrival', 'item_id_set')
    pass
    # ### end Alembic commands ###
