"""Modify comment and set default column 2023-01-03

Revision ID: 48bbd3459a9c
Revises: 5778bb849c28
Create Date: 2023-01-03 14:39:31.623053

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48bbd3459a9c'
down_revision = '5778bb849c28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_account', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_base', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_group', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_role', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_asset_depreciation', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_base', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_group', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set_item', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_type', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_kitting', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_maker', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_operation', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_outsourcing_company', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_role', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_role_operation', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_supplier', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_arrive', 'arrive_type',
                    existing_type=mysql.TINYINT(display_width=1),
                    nullable=False,
                    comment='入荷方法:0：発注,1：持ち込み',
                    existing_comment='入荷方法:order：発注,bring：持ち込み',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_arrive', 'record_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='計上方式',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_arrive', 'inspection_status',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    comment='検品ステータス:0：未,1：合格,2：不合格',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_arrive', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item', 'asset_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    comment='資産区分:0：償却資産(PCセット)、1：償却資産(PC,機器)、2：償却資産(ソフトウェア)、3：消耗品、4：リース、5：レンタル',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'asset_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='資産区分:0：償却資産(PCセット),1：償却資産(P,機器),2：償却資産(ソフトウェア),3：消耗品,4：リース,5：レンタル',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'record_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='計上方式',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_disposal', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification_to', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_order', 'record_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='計上方式',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'shipping_reception_status',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    comment='出荷受付ステータス',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'shipping_status',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    comment='出荷ステータス',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account', 'account_status',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    comment='ステータス:0：仮登録、1：本登録、2：削除',
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_order', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_pick_up', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_procurement', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_repairing', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_use', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_comment='削除者',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_procurement', 'procurement_status',
                    existing_type=mysql.INTEGER(),
                    comment='調達ステータス:0：作成中、1：見積依頼、2：見積回答、3：承認依頼、4：承認済、5：発注依頼、6：発注済、7：無効（削除）',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.drop_column('t_notification', 'notification_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_use', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_repairing', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_procurement', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_pick_up', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_order', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_order', 'record_type',
                    existing_type=mysql.VARCHAR(
                        charset='utf8mb4', collation='utf8mb4_unicode_ci', length=36),
                    nullable=True,
                    existing_comment='計上方式')
    op.alter_column('t_notification_to', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_disposal', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'record_type',
                    existing_type=mysql.VARCHAR(
                        charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
                    nullable=True,
                    existing_comment='計上方式')
    op.alter_column('t_asset', 'asset_type',
                    existing_type=mysql.VARCHAR(
                        charset='utf8mb4', collation='utf8mb4_unicode_ci', length=50),
                    nullable=True,
                    existing_comment='資産区分:0：償却資産(PCセット),1：償却資産(P,機器),2：償却資産(ソフトウェア),3：消耗品,4：リース,5：レンタル')
    op.alter_column('t_arrive', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_arrive', 'record_type',
                    existing_type=mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=50),
                    nullable=True,
                    existing_comment='計上方式')
    op.alter_column('t_arrive', 'arrive_type',
                    existing_type=mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=50),
                    nullable=True,
                    comment='入荷方法:order：発注,bring：持ち込み',
                    existing_comment='入荷方法:0：発注,1：持ち込み')
    op.alter_column('m_supplier', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_role_operation', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_role', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_outsourcing_company', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_operation', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_maker', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_kitting', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_type', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set_item', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_group', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_base', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_asset_depreciation', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_role', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_group', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_base', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_account', 'is_deleted',
                    existing_type=mysql.TINYINT(display_width=1),
                    comment='削除者',
                    existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
