"""Modify item master add column serial number database 2022-12-26

Revision ID: 4d56745e1644
Revises: 5afafb3c0b2b
Create Date: 2022-12-26 15:44:50.873706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d56745e1644'
down_revision = '5afafb3c0b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_item', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.drop_column('t_arrive_asset', 'asset_type')
    op.drop_column('t_arrive_asset', 'serial_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_arrive_asset', sa.Column('serial_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('t_arrive_asset', sa.Column('asset_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_column('m_item', 'serial_number')
    # ### end Alembic commands ###
