"""Edit comment 2023-01-12

Revision ID: 4d948f7e8c80
Revises: efe0cab25616
Create Date: 2023-01-12 10:42:16.589050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d948f7e8c80'
down_revision = 'efe0cab25616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_account', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_base', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_group', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_role', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_asset_depreciation', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_base', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_group', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set_item', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_type', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_kitting', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_maker', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_operation', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_outsourcing_company', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_role', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_role_operation', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_supplier', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'asset_status',
               existing_type=mysql.INTEGER(),
               comment='資産ステータス:0：在庫(stock), 1：キッティング中(kitting), 2：出荷中(shipping), 3：集荷中(pickingup), 4：修理中(repairing), 5：廃棄中(disposing), 6：利用中(using), 7：廃棄済み(disposed)',
               existing_comment='資産ステータス:stock：在庫,shipping instruction：出荷指示,waiting_kitting：キッティング待ち,kitting：キッティング中,waiting_shipping：出荷待ち,shipped：出荷済,using：利用中,waiting_pickup：集荷待ち,picked_up：集荷済,waiting_repair：修理待ち,being_repaired：修理中,repaired：修理済,waiting_disposal：廃棄待ち,disposing：廃棄中,disposed：廃棄済,depreciation_completed：償却完了,lease_up：リース切れ,rental_return：レンタル返却済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_disposal', 'disposal_status',
               existing_type=mysql.INTEGER(),
               comment='廃棄ステータス: 0：未, 1：中, 2：完了',
               existing_comment='廃棄ステータス',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_disposal', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_kitting', 'kitting_status',
               existing_type=mysql.INTEGER(),
               comment='キッティングステータス: 0：未, 1：中, 2：完了',
               existing_comment='キッティングステータス',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_kitting', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification_to', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_order', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_pick_up', 'pick_up_status',
               existing_type=mysql.INTEGER(),
               comment='集荷ステータス: 0：未, 1：中, 2：完了',
               existing_comment='集荷ステータス',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_pick_up', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_procurement', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_repairing', 'repairing_status',
               existing_type=mysql.INTEGER(),
               comment='修理ステータス: 0：未, 1：中, 2：完了',
               existing_comment='修理ステータス',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_repairing', 'outsourcing_company_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='委託先ID')
    op.alter_column('t_repairing', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'shipping_status',
               existing_type=mysql.INTEGER(),
               comment='出荷ステータス: 0：未, 1：中, 2：完了',
               existing_comment='出荷ステータス',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_use', 'use_status',
               existing_type=mysql.INTEGER(),
               comment='利用ステータス: 0：未, 1：中, 2：完了',
               existing_comment='利用ステータス',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_use', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_use', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_use', 'use_status',
               existing_type=mysql.INTEGER(),
               comment='利用ステータス',
               existing_comment='利用ステータス: 0：未, 1：中, 2：完了',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'shipping_status',
               existing_type=mysql.INTEGER(),
               comment='出荷ステータス',
               existing_comment='出荷ステータス: 0：未, 1：中, 2：完了',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_repairing', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_repairing', 'outsourcing_company_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='委託先ID')
    op.alter_column('t_repairing', 'repairing_status',
               existing_type=mysql.INTEGER(),
               comment='修理ステータス',
               existing_comment='修理ステータス: 0：未, 1：中, 2：完了',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_procurement', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_pick_up', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_pick_up', 'pick_up_status',
               existing_type=mysql.INTEGER(),
               comment='集荷ステータス',
               existing_comment='集荷ステータス: 0：未, 1：中, 2：完了',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_order', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification_to', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_notification', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_kitting', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_kitting', 'kitting_status',
               existing_type=mysql.INTEGER(),
               comment='キッティングステータス',
               existing_comment='キッティングステータス: 0：未, 1：中, 2：完了',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_disposal', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_disposal', 'disposal_status',
               existing_type=mysql.INTEGER(),
               comment='廃棄ステータス',
               existing_comment='廃棄ステータス: 0：未, 1：中, 2：完了',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'asset_status',
               existing_type=mysql.INTEGER(),
               comment='資産ステータス:stock：在庫,shipping instruction：出荷指示,waiting_kitting：キッティング待ち,kitting：キッティング中,waiting_shipping：出荷待ち,shipped：出荷済,using：利用中,waiting_pickup：集荷待ち,picked_up：集荷済,waiting_repair：修理待ち,being_repaired：修理中,repaired：修理済,waiting_disposal：廃棄待ち,disposing：廃棄中,disposed：廃棄済,depreciation_completed：償却完了,lease_up：リース切れ,rental_return：レンタル返却済',
               existing_comment='資産ステータス:0：在庫(stock), 1：キッティング中(kitting), 2：出荷中(shipping), 3：集荷中(pickingup), 4：修理中(repairing), 5：廃棄中(disposing), 6：利用中(using), 7：廃棄済み(disposed)',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_supplier', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_role_operation', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_role', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_outsourcing_company', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_operation', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_maker', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_kitting', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_type', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set_item', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item_set', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_item', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_group', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_base', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_asset_depreciation', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_role', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_group', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account_base', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('m_account', 'is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='登録旗deleted: 0: 消去未 ,1: 消去済',
               existing_comment='登録旗deleted: 0：消去未 ,1：消去済',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
