"""Delete column use_start_day into table t_shipping and add column use_start_date into table t_asset

Revision ID: 4e6ccac454da
Revises: b148b09470d7
Create Date: 2023-02-16 13:58:17.041738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6ccac454da'
down_revision = 'b148b09470d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_asset', sa.Column(
        'use_start_date', sa.DateTime(), nullable=True))
    op.drop_column('t_shipping', 'use_start_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_asset', 'use_start_date')
    # ### end Alembic commands ###
