"""Change table m_asset_depreciation to t_asset_depreciation and add table m_depreciation_rule

Revision ID: 54794a77e31e
Revises: 771a17874e70
Create Date: 2023-02-21 10:31:08.280427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54794a77e31e'
down_revision = '771a17874e70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_depreciation_rule',
                    sa.Column('depreciation_rule_id',
                              sa.Integer(), nullable=False),
                    sa.Column('depreciation_rule_name',
                              sa.String(length=100), nullable=True),
                    sa.Column('fiscal_year', sa.CHAR(length=4),
                              nullable=True, comment='年度:YYYY'),
                    sa.Column('amount', sa.Float(),
                              nullable=True, comment='費用'),
                    sa.Column('amount_per_year', sa.Float(),
                              nullable=True, comment='費用'),
                    sa.PrimaryKeyConstraint('depreciation_rule_id')
                    )
    op.create_table('t_asset_depreciation',
                    sa.Column('asset_depreciation_id',
                              sa.Integer(), nullable=False),
                    sa.Column('asset_id', sa.Integer(),
                              nullable=True, comment='資産ID'),
                    sa.Column('depreciation_rule_id',
                              sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(), server_default=sa.text(
                        '1'), nullable=False, comment='バージョン:楽観的排他で利用'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', sa.Integer(), nullable=True,
                              comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', sa.Integer(), nullable=True,
                              comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', sa.DateTime(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', sa.Integer(),
                              nullable=True, comment='削除者'),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['depreciation_rule_id'], [
                        'm_depreciation_rule.depreciation_rule_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('asset_depreciation_id')
                    )
    op.drop_table('m_asset_depreciation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_asset_depreciation',
                    sa.Column('asset_id', mysql.INTEGER(
                    ), autoincrement=False, nullable=False, comment='資産ID'),
                    sa.Column('fiscal_year', mysql.CHAR(
                        charset='utf8mb4', collation='utf8mb4_unicode_ci', length=4), nullable=True, comment='年度:YYYY'),
                    sa.Column('amount', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='費用'),
                    sa.Column('version', mysql.INTEGER(), server_default=sa.text(
                        "'1'"), autoincrement=False, nullable=False, comment='バージョン:楽観的排他で利用'),
                    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', mysql.DATETIME(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', mysql.INTEGER(),
                              autoincrement=False, nullable=True, comment='削除者'),
                    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], name='m_asset_depreciation_ibfk_1'),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], name='m_asset_depreciation_ibfk_2'),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], name='m_asset_depreciation_ibfk_3'),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], name='m_asset_depreciation_ibfk_4'),
                    sa.PrimaryKeyConstraint('asset_id'),
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('t_asset_depreciation')
    op.drop_table('m_depreciation_rule')
    # ### end Alembic commands ###
