"""table item master delete image column 2022-23-12

Revision ID: 5afafb3c0b2b
Revises: 79566c5b2d4c
Create Date: 2022-12-23 15:19:52.921441

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5afafb3c0b2b'
down_revision = '79566c5b2d4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_arrive_asset_ibfk_6',
                       't_arrive_asset', type_='foreignkey')
    op.drop_column('t_arrive_asset', 'maker_model')
    op.drop_column('t_arrive_asset', 'maker_id')
    op.drop_column('t_arrive_asset', 'item_name')
    op.drop_column('t_arrive_asset', 'jan_code')
    op.alter_column('t_procurement', 'total_amount',
                    existing_type=mysql.BIGINT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_procurement', 'total_amount',
                    existing_type=mysql.BIGINT(),
                    nullable=False)
    op.add_column('t_arrive_asset', sa.Column('jan_code', mysql.VARCHAR(
        collation='utf8mb4_unicode_ci', length=13), nullable=True))
    op.add_column('t_arrive_asset', sa.Column('item_name', mysql.VARCHAR(
        collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.add_column('t_arrive_asset', sa.Column(
        'maker_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('t_arrive_asset', sa.Column('maker_model', mysql.VARCHAR(
        collation='utf8mb4_unicode_ci', length=200), nullable=True))
    op.create_foreign_key('t_arrive_asset_ibfk_6', 't_arrive_asset', 'm_maker', [
                          'maker_id'], ['maker_id'])
    # ### end Alembic commands ###
