"""Modify table arrival 2023-01-04

Revision ID: 647e4b1c5cc3
Revises: 48bbd3459a9c
Create Date: 2023-01-04 11:43:17.637421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '647e4b1c5cc3'
down_revision = '48bbd3459a9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_arrival',
                    sa.Column('arrival_id', sa.Integer(),
                              nullable=False, comment='資産ID:資産登録前だが資産IDとする'),
                    sa.Column('arrival_code', sa.String(length=200),
                              nullable=True, comment='資産コード'),
                    sa.Column('is_asset', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='資産登録フラグ:0：未、1：済'),
                    sa.Column('inspection_status', sa.Integer(), server_default=sa.text(
                        '0'), nullable=False, comment='検品ステータス:0：未,1：合格,2：不合格'),
                    sa.Column('inspection_status_note', sa.String(
                        length=400), nullable=True, comment='検査ステータスノート'),
                    sa.Column('inspection_date', sa.Date(),
                              nullable=True, comment='検査日'),
                    sa.Column('inspection_account_id', sa.Integer(),
                              nullable=True, comment='検品担当者'),
                    sa.Column('asset_approve_account_id',
                              sa.Integer(), nullable=True),
                    sa.Column('failure_action', sa.Integer(), server_default=sa.text('0'), nullable=False,
                              comment='不合格処理:0：未,1：返品(再入荷待ち),2：返品(再入荷済),3：返品(再入荷なし)'),
                    sa.Column('failure_action_note', sa.String(length=400),
                              nullable=True, comment='障害アクションノート'),
                    sa.Column('order_id', sa.Integer(),
                              nullable=True, comment='発注明細ID'),
                    sa.Column('item_id', sa.Integer(),
                              nullable=True, comment='品目ID'),
                    sa.Column('item_name_kana', sa.String(length=400),
                              nullable=True, comment='品目名称カナ'),
                    sa.Column('item_type_id', sa.Integer(),
                              nullable=True, comment='タイプID'),
                    sa.Column('price', sa.Integer(),
                              nullable=True, comment='単価'),
                    sa.Column('base_id', sa.Integer(),
                              nullable=True, comment='入荷拠点ID'),
                    sa.Column('arrival_type', sa.Integer(), server_default=sa.text(
                        '0'), nullable=False, comment='入荷方法:0：発注,1：持ち込み'),
                    sa.Column('arrival_on', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='入荷日'),
                    sa.Column('record_type', sa.Integer(), server_default=sa.text(
                        '0'), nullable=False, comment='計上方式'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', sa.Integer(), nullable=True,
                              comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', sa.Integer(), nullable=True,
                              comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', sa.DateTime(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', sa.Integer(),
                              nullable=True, comment='削除者'),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(['asset_approve_account_id'], [
                        'm_account.account_id'], ),
                    sa.ForeignKeyConstraint(['base_id'], ['m_base.base_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['inspection_account_id'], [
                        'm_account.account_id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['m_item.item_id'], ),
                    sa.ForeignKeyConstraint(
                        ['item_type_id'], ['m_item_type.item_type_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['t_order.order_id'], ),
                    sa.PrimaryKeyConstraint('arrival_id')
                    )
    op.drop_table('t_arrive')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_arrive',
                    sa.Column('arrive_id', mysql.INTEGER(), autoincrement=True,
                              nullable=False, comment='資産ID:資産登録前だが資産IDとする'),
                    sa.Column('arrive_code', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='資産コード'),
                    sa.Column('is_asset', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='資産登録フラグ:0：未、1：済'),
                    sa.Column('inspection_status', mysql.INTEGER(), server_default=sa.text(
                        "'0'"), nullable=False, comment='検品ステータス:0：未,1：合格,2：不合格'),
                    sa.Column('inspection_date', sa.DATE(),
                              nullable=True, comment='検査日'),
                    sa.Column('inspection_account_id', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=32), nullable=True, comment='検品担当者'),
                    sa.Column('failure_action', mysql.INTEGER(), server_default=sa.text("'0'"), nullable=False,
                              comment='不合格処理:0：未,1：返品(再入荷待ち),2：返品(再入荷済),3：返品(再入荷なし)'),
                    sa.Column('order_id', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='発注明細ID'),
                    sa.Column('item_id', mysql.INTEGER(), autoincrement=True,
                              nullable=False, comment='品目ID'),
                    sa.Column('item_name_kana', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=400), nullable=True, comment='品目名称カナ'),
                    sa.Column('item_type_id', mysql.INTEGER(),
                              autoincrement=False, nullable=True, comment='タイプID'),
                    sa.Column('price', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='単価'),
                    sa.Column('base_id', mysql.INTEGER(), autoincrement=False,
                              nullable=False, comment='入荷拠点ID'),
                    sa.Column('arrive_type', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='入荷方法:0：発注,1：持ち込み'),
                    sa.Column('arrival_on', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='入荷日'),
                    sa.Column('registered_by', mysql.VARCHAR(
                        collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='資産登録者'),
                    sa.Column('registered_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='資産登録日時'),
                    sa.Column('record_type', mysql.INTEGER(), server_default=sa.text(
                        "'0'"), nullable=False, comment='計上方式'),
                    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text(
                        'CURRENT_TIMESTAMP'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', mysql.INTEGER(), autoincrement=False,
                              nullable=True, comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', mysql.DATETIME(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', mysql.INTEGER(),
                              autoincrement=False, nullable=True, comment='削除者'),
                    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text(
                        "'0'"), autoincrement=False, nullable=False, comment='登録旗deleted: 0：消去未 ,1：消去済'),
                    sa.ForeignKeyConstraint(
                        ['base_id'], ['m_base.base_id'], name='t_arrive_ibfk_1'),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], name='t_arrive_ibfk_2'),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], name='t_arrive_ibfk_3'),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['m_item.item_id'], name='t_arrive_ibfk_4'),
                    sa.ForeignKeyConstraint(
                        ['item_type_id'], ['m_item_type.item_type_id'], name='t_arrive_ibfk_5'),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], name='t_arrive_ibfk_6'),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['t_order.order_id'], name='t_arrive_ibfk_7'),
                    sa.PrimaryKeyConstraint('arrive_id'),
                    mysql_collate='utf8mb4_unicode_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.drop_table('t_arrival')
    # ### end Alembic commands ###
