"""Modify column 2023-01-30

Revision ID: 65d7f55379c6
Revises: 459b6436026e
Create Date: 2023-01-30 10:25:24.328857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65d7f55379c6'
down_revision = '459b6436026e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_asset_set', 'item_set_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    op.alter_column('m_item_set', 'item_set_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    op.alter_column('t_shipping', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    existing_comment='委託先ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_shipping', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('m_item_set', 'item_set_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    op.alter_column('m_asset_set', 'item_set_type',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    # ### end Alembic commands ###
