"""Create columns shipping_reception_type, use_start_day, estimated_shipping_date, shipping_late into t_shipping

Revision ID: 6d58845d9432
Revises: 0f34143e1a71
Create Date: 2023-02-13 13:09:40.578504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d58845d9432'
down_revision = '0f34143e1a71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_shipping', sa.Column('shipping_reception_type', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('t_shipping', sa.Column('use_start_day', sa.Date(), nullable=True))
    op.add_column('t_shipping', sa.Column('estimated_shipping_date', sa.Date(), nullable=True))
    op.add_column('t_shipping', sa.Column('shipping_late', sa.Boolean(), server_default=sa.text('False'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_shipping', 'shipping_late')
    op.drop_column('t_shipping', 'estimated_shipping_date')
    op.drop_column('t_shipping', 'use_start_day')
    op.drop_column('t_shipping', 'shipping_reception_type')
    # ### end Alembic commands ###
