"""Modify model

Revision ID: 6f105b7b132f
Revises: 230b53d61f82
Create Date: 2023-02-08 15:12:20.691424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f105b7b132f'
down_revision = '230b53d61f82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_pick_up', 'pick_up_arrangement_on',
                    existing_type=sa.DateTime(),
                    nullable=False,
                    existing_server_default=sa.text('now()'),
                    existing_comment='集荷手配日')
    op.alter_column('t_pick_up', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('t_shipping', 'reception_on',
                    existing_type=sa.DateTime(),
                    nullable=False,
                    existing_server_default=sa.text('now()'),
                    existing_comment='受付日')
    op.alter_column('t_shipping', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_shipping', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('t_shipping', 'reception_on',
                    existing_type=sa.DateTime(),
                    nullable=False,
                    existing_server_default=sa.text('now()'),
                    existing_comment='受付日')
    op.alter_column('t_pick_up', 'outsourcing_company_id',
                    existing_type=mysql.INTEGER(),
                    nullable=True,
                    existing_comment='委託先ID')
    op.alter_column('t_pick_up', 'pick_up_arrangement_on',
                    existing_type=sa.DateTime(),
                    nullable=False,
                    existing_server_default=sa.text('now()'),
                    existing_comment='集荷手配日')
    # ### end Alembic commands ###
