"""Edit comment column asset_type in tables m_item and t_asset

Revision ID: 70ee629a8207
Revises: 1ac043b1fc40
Create Date: 2023-02-24 10:36:04.897869

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70ee629a8207'
down_revision = '1ac043b1fc40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_item', 'asset_type',
                    existing_type=mysql.INTEGER(),
                    comment='資産区分:0：一般、1：ライセンス',
                    existing_comment='資産区分:0：償却資産(PCセット)、1：償却資産(PC,機器)、2：償却資産(ソフトウェア)、3：消耗品、4：リース、5：レンタル',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('t_asset', 'asset_type',
                    existing_type=mysql.INTEGER(),
                    comment='資産区分:0：一般、1：ライセンス',
                    existing_comment='資産区分:0：償却資産(PCセット),1：償却資産(P,機器),2：償却資産(ソフトウェア),3：消耗品,4：リース,5：レンタル',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_asset', 'asset_type',
                    existing_type=mysql.INTEGER(),
                    comment='資産区分:0：償却資産(PCセット),1：償却資産(P,機器),2：償却資産(ソフトウェア),3：消耗品,4：リース,5：レンタル',
                    existing_comment='資産区分:0：一般、1：ライセンス',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('m_item', 'asset_type',
                    existing_type=mysql.INTEGER(),
                    comment='資産区分:0：償却資産(PCセット)、1：償却資産(PC,機器)、2：償却資産(ソフトウェア)、3：消耗品、4：リース、5：レンタル',
                    existing_comment='資産区分:0：一般、1：ライセンス',
                    existing_nullable=False,
                    existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
