"""Add database 2022-12-22

Revision ID: 79566c5b2d4c
Revises: 
Create Date: 2022-12-22 12:55:52.105210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79566c5b2d4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_account',
                    sa.Column('account_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_cd', sa.String(
                        length=100), nullable=True),
                    sa.Column('ext_account_id', sa.Integer(), nullable=True),
                    sa.Column('account_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('email_address', sa.String(
                        length=100), nullable=True),
                    sa.Column('account_status', sa.Integer(), nullable=False),
                    sa.Column('is_system_manager', sa.Boolean(),
                              server_default='0', nullable=False),
                    sa.Column('created_datetime', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_datetime',
                              sa.DateTime(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('account_id')
                    )
    op.create_table('m_prefecture',
                    sa.Column('pref_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('pref_name', sa.String(
                        length=200), nullable=True),
                    sa.PrimaryKeyConstraint('pref_id')
                    )
    op.create_table('m_base',
                    sa.Column('base_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('base_cd', sa.String(length=200), nullable=True),
                    sa.Column('base_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('zip_code', sa.String(length=10), nullable=True),
                    sa.Column('pref_code', sa.Integer(), nullable=True),
                    sa.Column('address', sa.String(length=400), nullable=True),
                    sa.Column('addressee', sa.String(
                        length=200), nullable=True),
                    sa.Column('telephone_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('fax_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('e_mail_address', sa.String(
                        length=200), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['pref_code'], ['m_prefecture.pref_id'], ),
                    sa.PrimaryKeyConstraint('base_id')
                    )
    op.create_table('m_group',
                    sa.Column('group_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('group_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('group_cd', sa.String(
                        length=200), nullable=True),
                    sa.Column('parent_group_id', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('group_id')
                    )
    op.create_table('m_item_type',
                    sa.Column('item_type_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('item_type_name', sa.String(
                        length=400), nullable=True),
                    sa.Column('can_be_main', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.Column('sort_order', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('item_type_id')
                    )
    op.create_table('m_kitting',
                    sa.Column('kitting_master_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('kitting_master_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('kitting_master_id')
                    )
    op.create_table('m_maker',
                    sa.Column('maker_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('maker_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('sort_order', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('area', sa.String(length=200), nullable=True),
                    sa.Column('zip_code', sa.String(length=10), nullable=True),
                    sa.Column('pref_code', sa.Integer(), nullable=True),
                    sa.Column('city', sa.String(length=200), nullable=True),
                    sa.Column('street', sa.String(length=200), nullable=True),
                    sa.Column('building', sa.String(
                        length=200), nullable=True),
                    sa.Column('pilot_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('department', sa.String(
                        length=200), nullable=True),
                    sa.Column('pic', sa.String(length=200), nullable=True),
                    sa.Column('direct_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('direct_email_address', sa.String(
                        length=200), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['pref_code'], ['m_prefecture.pref_id'], ),
                    sa.PrimaryKeyConstraint('maker_id')
                    )
    op.create_table('m_operation',
                    sa.Column('operation_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('operation_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('operation_id')
                    )
    op.create_table('m_outsourcing_company',
                    sa.Column('outsourcing_company_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('outsourcing_company_name',
                              sa.String(length=200), nullable=True),
                    sa.Column('area', sa.String(length=50), nullable=True),
                    sa.Column('zip_code', sa.String(length=10), nullable=True),
                    sa.Column('pref_code', sa.Integer(), nullable=True),
                    sa.Column('city', sa.String(length=200), nullable=True),
                    sa.Column('street', sa.String(length=200), nullable=True),
                    sa.Column('building', sa.String(
                        length=200), nullable=True),
                    sa.Column('pilot_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('department', sa.String(
                        length=200), nullable=True),
                    sa.Column('pic', sa.String(length=200), nullable=True),
                    sa.Column('direct_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('direct_email_address', sa.String(
                        length=200), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('sort_order', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['pref_code'], ['m_prefecture.pref_id'], ),
                    sa.PrimaryKeyConstraint('outsourcing_company_id')
                    )
    op.create_table('m_role',
                    sa.Column('role_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('role_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('role_id')
                    )
    op.create_table('m_supplier',
                    sa.Column('supplier_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('supplier_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('zip_code', sa.String(length=10), nullable=True),
                    sa.Column('pref_code', sa.Integer(), nullable=True),
                    sa.Column('city', sa.String(length=200), nullable=True),
                    sa.Column('street', sa.String(length=200), nullable=True),
                    sa.Column('building', sa.String(
                        length=200), nullable=True),
                    sa.Column('pilot_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('department', sa.String(
                        length=200), nullable=True),
                    sa.Column('pic', sa.String(length=200), nullable=True),
                    sa.Column('direct_number', sa.String(
                        length=200), nullable=True),
                    sa.Column('direct_email_address', sa.String(
                        length=200), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('sort_order', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['pref_code'], ['m_prefecture.pref_id'], ),
                    sa.PrimaryKeyConstraint('supplier_id')
                    )
    op.create_table('t_notification',
                    sa.Column('notification_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('notification_cd', sa.String(
                        length=36), nullable=True),
                    sa.Column('title', sa.String(length=200), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('notification_at', sa.DateTime(), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('notification_id')
                    )
    op.create_table('t_procurement',
                    sa.Column('procurement_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('procurement_name', sa.String(
                        length=200), nullable=False),
                    sa.Column('procurement_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('is_back', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.Column('quotation_requester', sa.String(
                        length=36), nullable=True),
                    sa.Column('quotation_request_note', sa.String(
                        length=2000), nullable=True),
                    sa.Column('quotation_request_datetime',
                              sa.DateTime(), nullable=True),
                    sa.Column('quotation_account_id',
                              sa.Integer(), nullable=True),
                    sa.Column('quotation_note', sa.String(
                        length=2000), nullable=True),
                    sa.Column('quotation_datetime',
                              sa.DateTime(), nullable=True),
                    sa.Column('approval_requester', sa.String(
                        length=36), nullable=True),
                    sa.Column('approval_expiration_date',
                              sa.Date(), nullable=True),
                    sa.Column('approval_request_note', sa.String(
                        length=2000), nullable=True),
                    sa.Column('approval_request_datetime',
                              sa.DateTime(), nullable=True),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('approval_note', sa.String(
                        length=2000), nullable=True),
                    sa.Column('approval_datetime',
                              sa.DateTime(), nullable=True),
                    sa.Column('ext_approval_id', sa.String(
                        length=100), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.Column('total_amount', sa.BIGINT(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['quotation_account_id'], [
                        'm_account.account_id'], ),
                    sa.PrimaryKeyConstraint('procurement_id')
                    )
    op.create_table('m_account_base',
                    sa.Column('account_base_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('base_id', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['base_id'], ['m_base.base_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('account_base_id')
                    )
    op.create_table('m_account_group',
                    sa.Column('account_group_id',
                              sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('is_manager', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['m_group.group_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('account_group_id')
                    )
    op.create_table('m_account_role',
                    sa.Column('account_id', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['m_role.role_id'], ),
                    sa.PrimaryKeyConstraint('account_id')
                    )
    op.create_table('m_item',
                    sa.Column('item_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('item_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('jan_code', sa.String(length=13), nullable=True),
                    sa.Column('maker_id', sa.Integer(), nullable=True),
                    sa.Column('maker_model', sa.String(
                        length=200), nullable=True),
                    sa.Column('asset_type', sa.String(
                        length=36), nullable=True),
                    sa.Column('expiration_date_from',
                              sa.Date(), nullable=True),
                    sa.Column('expiration_date_to', sa.Date(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('os_id', sa.String(length=36), nullable=True),
                    sa.Column('order_unit', sa.Integer(), nullable=True),
                    sa.Column('order_unit_max', sa.Integer(), nullable=True),
                    sa.Column('item_title', sa.String(
                        length=200), nullable=True),
                    sa.Column('item_description', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['maker_id'], ['m_maker.maker_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('item_id')
                    )
    op.create_table('m_item_set',
                    sa.Column('item_id_set', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('item_set_type', sa.String(
                        length=36), nullable=True),
                    sa.Column('item_set_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('item_set_jan_code', sa.String(
                        length=13), nullable=True),
                    sa.Column('item_set_maker_id',
                              sa.Integer(), nullable=True),
                    sa.Column('item_set_maker_model', sa.String(
                        length=200), nullable=True),
                    sa.Column('item_set_os', sa.String(
                        length=36), nullable=True),
                    sa.Column('item_set_expiration_date_from',
                              sa.Date(), nullable=True),
                    sa.Column('item_set_expiration_date_to',
                              sa.Date(), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['item_set_maker_id'], [
                                            'm_maker.maker_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('item_id_set')
                    )
    op.create_table('m_role_operation',
                    sa.Column('role_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('operation_id', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['operation_id'], ['m_operation.operation_id'], ),
                    sa.PrimaryKeyConstraint('role_id')
                    )
    op.create_table('t_asset',
                    sa.Column('asset_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('asset_name_kana', sa.String(
                        length=500), nullable=True),
                    sa.Column('asset_cd', sa.String(
                        length=100), nullable=True),
                    sa.Column('asset_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('asset_kind', sa.String(
                        length=50), nullable=True),
                    sa.Column('asset_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('asset_from', sa.Date(), nullable=True),
                    sa.Column('asset_to', sa.Date(), nullable=True),
                    sa.Column('parent_asset_id', sa.Integer(), nullable=True),
                    sa.Column('record_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('kitting_history_id',
                              sa.Integer(), nullable=True),
                    sa.Column('kitting_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('shipping_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('base_id', sa.Integer(), nullable=True),
                    sa.Column('repairing_status', sa.Integer(),
                              server_default='0', nullable=False),
                    sa.Column('disposal_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('disposal_on', sa.Date(), nullable=True),
                    sa.Column('returned_on', sa.Date(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['base_id'], ['m_base.base_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['m_group.group_id'], ),
                    sa.ForeignKeyConstraint(['kitting_history_id'], [
                        'm_kitting.kitting_master_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('asset_id')
                    )
    op.create_table('t_notification_to',
                    sa.Column('notification_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('notification_to_type', sa.String(
                        length=100), nullable=True),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('base_id', sa.Integer(), nullable=True),
                    sa.Column('notification_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['base_id'], ['m_base.base_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['m_group.group_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('notification_id')
                    )
    op.create_table('m_asset_depreciation',
                    sa.Column('asset_id', sa.Integer(), nullable=False),
                    sa.Column('fiscal_year', sa.CHAR(length=4), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('asset_id')
                    )
    op.create_table('m_item_set_item',
                    sa.Column('item_set_item_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('item_id_set', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('is_main', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.Column('sort_order', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['m_item.item_id'], ),
                    sa.ForeignKeyConstraint(
                        ['item_id_set'], ['m_item_set.item_id_set'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('item_set_item_id')
                    )
    op.create_table('t_disposal',
                    sa.Column('disposal_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('disposal_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('disposal_id')
                    )
    op.create_table('t_order',
                    sa.Column('order_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('procurement_id', sa.Integer(), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('has_users_file', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('has_quotation_file', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('estimated_arrival_date',
                              sa.Date(), nullable=True),
                    sa.Column('estimated_shipping_date',
                              sa.Date(), nullable=True),
                    sa.Column('kitting_id', sa.Integer(), nullable=True),
                    sa.Column('record_type', sa.String(
                        length=36), nullable=True),
                    sa.Column('supplier_id', sa.Integer(), nullable=True),
                    sa.Column('order_on', sa.Date(), nullable=True),
                    sa.Column('supplier_order_id',
                              sa.Integer(), nullable=True),
                    sa.Column('has_order_file', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['m_item.item_id'], ),
                    sa.ForeignKeyConstraint(
                        ['kitting_id'], ['m_kitting.kitting_master_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['procurement_id'], [
                        't_procurement.procurement_id'], ),
                    sa.ForeignKeyConstraint(
                        ['supplier_id'], ['m_supplier.supplier_id'], ),
                    sa.ForeignKeyConstraint(['supplier_order_id'], [
                                            't_order.order_id'], ),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    op.create_table('t_pick_up',
                    sa.Column('pick_up_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('pick_up_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=True),
                    sa.Column('pick_up_arrangement_on',
                              sa.Date(), nullable=True),
                    sa.Column('pick_up_scheduled_date',
                              sa.Date(), nullable=True),
                    sa.Column('completed_on', sa.Date(), nullable=True),
                    sa.Column('outsourcing_company_id',
                              sa.Integer(), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['outsourcing_company_id'], [
                        'm_outsourcing_company.outsourcing_company_id'], ),
                    sa.PrimaryKeyConstraint('pick_up_id')
                    )
    op.create_table('t_repairing',
                    sa.Column('repairing_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('repairing_status', sa.Integer(),
                              server_default='0', nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('repairing_id')
                    )
    op.create_table('t_shipping',
                    sa.Column('shipping_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('shipping_reception_status',
                              sa.Integer(), nullable=False),
                    sa.Column('shipping_status', sa.Integer(), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=True),
                    sa.Column('reception_on', sa.Date(), nullable=True),
                    sa.Column('working_on', sa.Date(), nullable=True),
                    sa.Column('completed_on', sa.Date(), nullable=True),
                    sa.Column('outsourcing_company_id',
                              sa.Integer(), nullable=True),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['outsourcing_company_id'], [
                        'm_outsourcing_company.outsourcing_company_id'], ),
                    sa.PrimaryKeyConstraint('shipping_id')
                    )
    op.create_table('t_use',
                    sa.Column('use_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('use_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=True),
                    sa.Column('use_on_from', sa.Date(), nullable=True),
                    sa.Column('use_on_to', sa.Date(), nullable=True),
                    sa.Column('account_id', sa.Integer(), nullable=True),
                    sa.Column('group_id', sa.Integer(), nullable=True),
                    sa.Column('base_id', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(),
                              server_default=sa.text('1'), nullable=False),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(['base_id'], ['m_base.base_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['group_id'], ['m_group.group_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('use_id')
                    )
    op.create_table('t_arrive_asset',
                    sa.Column('arrive_asset_id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('arrive_asset_code', sa.String(
                        length=200), nullable=True),
                    sa.Column('is_asset', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.Column('inspection_status', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('inspection_account_id',
                              sa.String(length=36), nullable=True),
                    sa.Column('failure_action', sa.Integer(),
                              server_default=sa.text('0'), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=True),
                    sa.Column('asset_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('item_id', sa.Integer(), nullable=True),
                    sa.Column('item_name', sa.String(
                        length=200), nullable=True),
                    sa.Column('item_name_kana', sa.String(
                        length=400), nullable=True),
                    sa.Column('item_type_id', sa.Integer(), nullable=True),
                    sa.Column('maker_id', sa.Integer(), nullable=True),
                    sa.Column('maker_model', sa.String(
                        length=200), nullable=True),
                    sa.Column('jan_code', sa.String(length=13), nullable=True),
                    sa.Column('serial_number', sa.String(
                        length=100), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('base_id', sa.Integer(), nullable=True),
                    sa.Column('estimated_arrive_on', sa.Date(), nullable=True),
                    sa.Column('arrive_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('arrive_on', sa.Date(), nullable=True),
                    sa.Column('registered_by', sa.String(
                        length=100), nullable=True),
                    sa.Column('registered_at', sa.DateTime(), nullable=False),
                    sa.Column('record_type', sa.String(
                        length=50), nullable=True),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('created_by', sa.Integer(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('modified_by', sa.Integer(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_by', sa.Integer(), nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default=sa.text('False'), nullable=False),
                    sa.ForeignKeyConstraint(['base_id'], ['m_base.base_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['m_item.item_id'], ),
                    sa.ForeignKeyConstraint(
                        ['item_type_id'], ['m_item_type.item_type_id'], ),
                    sa.ForeignKeyConstraint(
                        ['maker_id'], ['m_maker.maker_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['t_order.order_id'], ),
                    sa.PrimaryKeyConstraint('arrive_asset_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_arrive_asset')
    op.drop_table('t_use')
    op.drop_table('t_shipping')
    op.drop_table('t_repairing')
    op.drop_table('t_pick_up')
    op.drop_table('t_order')
    op.drop_table('t_disposal')
    op.drop_table('m_item_set_item')
    op.drop_table('m_asset_depreciation')
    op.drop_table('t_notification_to')
    op.drop_table('t_asset')
    op.drop_table('m_role_operation')
    op.drop_table('m_item_set')
    op.drop_table('m_item')
    op.drop_table('m_account_role')
    op.drop_table('m_account_group')
    op.drop_table('m_account_base')
    op.drop_table('t_procurement')
    op.drop_table('t_notification')
    op.drop_table('m_supplier')
    op.drop_table('m_role')
    op.drop_table('m_outsourcing_company')
    op.drop_table('m_operation')
    op.drop_table('m_maker')
    op.drop_table('m_kitting')
    op.drop_table('m_item_type')
    op.drop_table('m_group')
    op.drop_table('m_base')
    op.drop_table('m_prefecture')
    op.drop_table('m_account')
    # ### end Alembic commands ###
