"""Modify column item_set_os into table m_item_set 2023-01-30

Revision ID: 96df6865a507
Revises: 65d7f55379c6
Create Date: 2023-01-30 15:33:13.142429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96df6865a507'
down_revision = '65d7f55379c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_item_set', 'item_set_os',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    op.alter_column('m_asset_set', 'item_set_os',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_asset_set', 'item_set_os',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    op.alter_column('m_item_set', 'item_set_os',
                    existing_type=mysql.INTEGER(),
                    nullable=False,
                    server_default=sa.text("'0'"))
    # ### end Alembic commands ###
