"""Set default arrival_on 2023-01-05

Revision ID: ac7c91f9c09b
Revises: 0a8639b17f37
Create Date: 2023-01-05 17:02:32.919079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7c91f9c09b'
down_revision = '0a8639b17f37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
