"""Add columns master_pc_number, kitting_method into table m_kitting

Revision ID: b148b09470d7
Revises: 158e6198d37a
Create Date: 2023-02-15 17:05:26.843464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b148b09470d7'
down_revision = '158e6198d37a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_kitting', sa.Column('master_pc_number', sa.Integer(), nullable=True, comment='マスターPC番号'))
    op.add_column('m_kitting', sa.Column('kitting_method', sa.String(length=50), nullable=True, comment='キッティング方法'))
    op.alter_column('t_repairing', 'note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='備考',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_repairing', 'note',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='備考',
               existing_nullable=True)
    op.drop_column('m_kitting', 'kitting_method')
    op.drop_column('m_kitting', 'master_pc_number')
    # ### end Alembic commands ###
