"""Add table m_gen_code

Revision ID: b55c6e6a30f1
Revises: a7411e8c1b00
Create Date: 2023-01-12 17:27:29.162038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b55c6e6a30f1'
down_revision = 'a7411e8c1b00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_gen_code',
                    sa.Column('gen_code_id', sa.Integer(), nullable=False),
                    sa.Column('table_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('field_name', sa.String(
                        length=50), nullable=True),
                    sa.Column('field_value', sa.Integer(), nullable=True),
                    sa.Column('field_display_label', sa.String(
                        length=50), nullable=True),
                    sa.PrimaryKeyConstraint('gen_code_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_gen_code')
    # ### end Alembic commands ###
