"""add table t_kitting, delete columns in table t_asset 2023-01-06

Revision ID: b7b666fd580f
Revises: ac7c91f9c09b
Create Date: 2023-01-06 13:18:34.875682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7b666fd580f'
down_revision = 'ac7c91f9c09b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_constraint('t_order_ibfk_4', 't_order', type_='foreignkey')
    op.drop_constraint('t_asset_ibfk_6', 't_asset', type_='foreignkey')
    op.drop_column('t_asset', 'kitting_history_id')
    op.drop_constraint('t_asset_ibfk_2', 't_asset', type_='foreignkey')
    op.drop_constraint('t_asset_ibfk_1', 't_asset', type_='foreignkey')
    op.drop_constraint('t_asset_ibfk_5', 't_asset', type_='foreignkey')
    op.drop_column('t_asset', 'group_id')
    op.drop_column('t_asset', 'returned_on')
    op.drop_column('t_asset', 'base_id')
    op.drop_column('t_asset', 'account_id')
    op.drop_column('t_asset', 'disposal_on')
    op.drop_column('t_asset', 'kitting_status')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_kitting',
                    sa.Column('kitting_id', sa.Integer(),
                              nullable=False, comment='キットID'),
                    sa.Column('kitting_status', sa.Integer(), server_default=sa.text(
                        '0'), nullable=False, comment='キッティングステータス'),
                    sa.Column('asset_id', sa.Integer(),
                              nullable=True, comment='資産ID'),
                    sa.Column('kitting_user_id', sa.Integer(),
                              nullable=True, comment='アカウントID'),
                    sa.Column('account_id', sa.Integer(),
                              nullable=True, comment='アカウントID'),
                    sa.Column('kitting_at', sa.DateTime(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(), nullable=True),
                    sa.Column('version', sa.Integer(), server_default=sa.text(
                        '1'), nullable=False, comment='バージョン:楽観的排他で利用'),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='作成日時:プログラムでは設定しない'),
                    sa.Column('created_by', sa.Integer(), nullable=True,
                              comment='作成処理:プログラムで設定、API名、関数名'),
                    sa.Column('modified_at', sa.DateTime(), server_default=sa.text(
                        'now()'), nullable=False, comment='更新日時:プログラムでは設定しない'),
                    sa.Column('modified_by', sa.Integer(), nullable=True,
                              comment='更新処理:プログラムで設定、API名、関数名'),
                    sa.Column('deleted_at', sa.DateTime(),
                              nullable=True, comment='削除日時'),
                    sa.Column('deleted_by', sa.Integer(),
                              nullable=True, comment='削除者'),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text(
                        'False'), nullable=False, comment='登録旗deleted: 0: 消去未 ,1: 消去済'),
                    sa.ForeignKeyConstraint(
                        ['account_id'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['asset_id'], ['t_asset.asset_id'], ),
                    sa.ForeignKeyConstraint(
                        ['created_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['deleted_by'], ['m_account.account_id'], ),
                    sa.ForeignKeyConstraint(['kitting_user_id'], [
                        'm_account.account_id'], ),
                    sa.ForeignKeyConstraint(
                        ['modified_by'], ['m_account.account_id'], ),
                    sa.PrimaryKeyConstraint('kitting_id')
                    )

    op.add_column('t_disposal', sa.Column('outsourcing_company_id',
                  sa.Integer(), nullable=False, comment='委託先ID'))
    op.create_foreign_key(None, 't_disposal', 'm_outsourcing_company', [
                          'outsourcing_company_id'], ['outsourcing_company_id'])
    op.create_foreign_key(None, 't_order', 't_kitting', [
                          'kitting_id'], ['kitting_id'])
    op.alter_column('t_procurement', 'procurement_name',
                    existing_type=mysql.VARCHAR(
                        charset='utf8mb4', collation='utf8mb4_unicode_ci', length=200),
                    nullable=True,
                    existing_comment='調達名称')
    op.add_column('t_repairing', sa.Column('outsourcing_company_id',
                  sa.Integer(), nullable=False, comment='委託先ID'))
    op.create_foreign_key(None, 't_repairing', 'm_outsourcing_company', [
                          'outsourcing_company_id'], ['outsourcing_company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_repairing', type_='foreignkey')
    op.drop_column('t_repairing', 'outsourcing_company_id')
    op.alter_column('t_procurement', 'procurement_name',
                    existing_type=mysql.VARCHAR(
                        charset='utf8mb4', collation='utf8mb4_unicode_ci', length=200),
                    nullable=False,
                    existing_comment='調達名称')
    op.drop_constraint(None, 't_order', type_='foreignkey')
    op.create_foreign_key('t_order_ibfk_4', 't_order', 'm_kitting', [
                          'kitting_id'], ['kitting_id'])
    op.drop_constraint(None, 't_disposal', type_='foreignkey')
    op.drop_column('t_disposal', 'outsourcing_company_id')
    op.add_column('t_asset', sa.Column('kitting_status', mysql.INTEGER(), server_default=sa.text(
        "'0'"), autoincrement=False, nullable=False, comment='キッティングステータス'))
    op.add_column('t_asset', sa.Column(
        'disposal_on', sa.DATE(), nullable=True, comment='廃棄日時'))
    op.add_column('t_asset', sa.Column('account_id', mysql.INTEGER(
    ), autoincrement=False, nullable=False, comment='利用者アカウントID'))
    op.add_column('t_asset', sa.Column('base_id', mysql.INTEGER(),
                  autoincrement=False, nullable=False, comment='利用拠点ID'))
    op.add_column('t_asset', sa.Column(
        'returned_on', sa.DATE(), nullable=True, comment='返却日時'))
    op.add_column('t_asset', sa.Column('group_id', mysql.INTEGER(),
                  autoincrement=False, nullable=False, comment='利用グループID'))
    op.add_column('t_asset', sa.Column('kitting_history_id', mysql.INTEGER(
    ), autoincrement=False, nullable=True, comment='キッティング履歴ID'))
    op.create_foreign_key('t_asset_ibfk_5', 't_asset',
                          'm_group', ['group_id'], ['group_id'])
    op.create_foreign_key('t_asset_ibfk_6', 't_asset', 'm_kitting', [
                          'kitting_history_id'], ['kitting_id'])
    op.create_foreign_key('t_asset_ibfk_1', 't_asset', 'm_account', [
                          'account_id'], ['account_id'])
    op.create_foreign_key('t_asset_ibfk_2', 't_asset',
                          'm_base', ['base_id'], ['base_id'])
    op.add_column('m_kitting', sa.Column('kitting_name', mysql.VARCHAR(charset='utf8mb4',
                  collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='キッティングマスタ名称'))
    op.add_column('m_kitting', sa.Column('kitting_id', mysql.INTEGER(
    ), autoincrement=True, nullable=False, comment='キッティングマスタID'))
    op.drop_column('m_kitting', 'kitting_master_name')
    op.drop_column('m_kitting', 'kitting_master_id')
    op.drop_table('t_kitting')
    # ### end Alembic commands ###
