"""Modify type column os_id in table m_item 2023-01-12

Revision ID: e2e73b49d50f
Revises: 4d948f7e8c80
Create Date: 2023-01-12 13:09:44.049601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2e73b49d50f'
down_revision = '4d948f7e8c80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_item', 'os_id',
               existing_type=mysql.INTEGER(),
               comment='OS',
               existing_comment='OS',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('m_item', 'os_id',
               existing_type=mysql.INTEGER(),
               comment='OS',
               existing_comment='OS',
               existing_nullable=True)
    # ### end Alembic commands ###
