"""Add ForeignKey account_id into tables t_pick_up, t_shipping and t_repairing

Revision ID: efe0cab25616
Revises: b7b666fd580f
Create Date: 2023-01-10 10:47:36.791714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe0cab25616'
down_revision = 'b7b666fd580f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_pick_up', sa.Column(
        'account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_pick_up', 'm_account',
                          ['account_id'], ['account_id'])
    op.add_column('t_shipping', sa.Column(
        'account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_shipping', 'm_account', [
                          'account_id'], ['account_id'])
    op.add_column('t_repairing', sa.Column(
        'account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_repairing', 'm_account', [
                          'account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_shipping', type_='foreignkey')
    op.drop_column('t_shipping', 'account_id')
    op.drop_constraint(None, 't_pick_up', type_='foreignkey')
    op.drop_column('t_pick_up', 'account_id')
    op.drop_constraint(None, 't_repairing', type_='foreignkey')
    op.drop_column('t_repairing', 'account_id')
    # ### end Alembic commands ###
