"""update serial_number

Revision ID: f1fb62d13dd5
Revises: 4d56745e1644
Create Date: 2022-12-27 15:32:27.370836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1fb62d13dd5'
down_revision = '4d56745e1644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_item', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('m_item', sa.Column('tax', sa.Integer(), nullable=True))
    op.add_column('m_item', sa.Column(
        'tax_inc_price', sa.Float(), nullable=True))
    op.drop_constraint('t_order_ibfk_8', 't_order', type_='foreignkey')
    op.drop_column('t_order', 'supplier_order_id')
    op.drop_column('t_order', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_order', sa.Column('price', mysql.INTEGER(),
                  autoincrement=False, nullable=False))
    op.add_column('t_order', sa.Column('supplier_order_id',
                  mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('t_order_ibfk_8', 't_order', 't_order', [
                          'supplier_order_id'], ['order_id'])
    op.drop_column('m_item', 'tax_inc_price')
    op.drop_column('m_item', 'tax')
    op.drop_column('m_item', 'price')
    # ### end Alembic commands ###
