"""Add column using into table t_asset

Revision ID: f49c7b4ec4ac
Revises: 4e6ccac454da
Create Date: 2023-02-16 17:32:16.043866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f49c7b4ec4ac'
down_revision = '4e6ccac454da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_asset', sa.Column(
        'using_from', sa.DateTime(), nullable=True))
    op.add_column('t_asset', sa.Column(
        'using_to', sa.DateTime(), nullable=True))
    op.drop_column('t_asset', 'use_start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_asset', sa.Column(
        'use_start_date', mysql.DATETIME(), nullable=True))
    op.drop_column('t_asset', 'using_to')
    op.drop_column('t_asset', 'using_from')
    # ### end Alembic commands ###
