import sys
import os
sys.path.insert(0, os.getcwd())
from chalicelib.models.models import GenCode
from chalicelib.models import session

gen_code = (
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=0,
            fieldDisplayLabel='在庫'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=1,
            fieldDisplayLabel='キッティング中'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=2,
            fieldDisplayLabel='出荷中'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=3,
            fieldDisplayLabel='集荷中'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=4,
            fieldDisplayLabel='修理中'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=5,
            fieldDisplayLabel='廃棄中'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=6,
            fieldDisplayLabel='利用中'),
    GenCode(tableName='t_asset', fieldName='assetStatus', fieldValue=7,
            fieldDisplayLabel='廃棄済み'),
    GenCode(tableName='t_kitting', fieldName='kittingStatus', fieldValue=0,
            fieldDisplayLabel='未キッティング'),
    GenCode(tableName='t_kitting', fieldName='kittingStatus', fieldValue=1,
            fieldDisplayLabel='キッティング中'),
    GenCode(tableName='t_kitting', fieldName='kittingStatus', fieldValue=2,
            fieldDisplayLabel='キッティング完了'),
    GenCode(tableName='t_shipping', fieldName='shippingStatus', fieldValue=0,
            fieldDisplayLabel='未出荷'),
    GenCode(tableName='t_shipping', fieldName='shippingStatus', fieldValue=1,
            fieldDisplayLabel='出荷中'),
    GenCode(tableName='t_shipping', fieldName='shippingStatus', fieldValue=2,
            fieldDisplayLabel='出荷完了'),
    GenCode(tableName='t_shipping', fieldName='shippingReceptionStatus', fieldValue=0,
            fieldDisplayLabel='未出荷受付'),
    GenCode(tableName='t_shipping', fieldName='shippingReceptionStatus', fieldValue=1,
            fieldDisplayLabel='出荷受付中'),
    GenCode(tableName='t_shipping', fieldName='shippingReceptionStatus', fieldValue=2,
            fieldDisplayLabel='出荷受付完了'),
    GenCode(tableName='t_pick_up', fieldName='pickUpStatus', fieldValue=0,
            fieldDisplayLabel='未集荷'),
    GenCode(tableName='t_pick_up', fieldName='pickUpStatus', fieldValue=1,
            fieldDisplayLabel='集荷中'),
    GenCode(tableName='t_pick_up', fieldName='pickUpStatus', fieldValue=2,
            fieldDisplayLabel='集荷完了'),
    GenCode(tableName='t_repairing', fieldName='repairingStatus', fieldValue=0,
            fieldDisplayLabel='未修理'),
    GenCode(tableName='t_repairing', fieldName='repairingStatus', fieldValue=1,
            fieldDisplayLabel='修理中'),
    GenCode(tableName='t_repairing', fieldName='repairingStatus', fieldValue=2,
            fieldDisplayLabel='修理完了'),
    GenCode(tableName='t_disposal', fieldName='disposalStatus', fieldValue=0,
            fieldDisplayLabel='未廃棄'),
    GenCode(tableName='t_disposal', fieldName='disposalStatus', fieldValue=1,
            fieldDisplayLabel='廃棄中'),
    GenCode(tableName='t_disposal', fieldName='disposalStatus', fieldValue=2,
            fieldDisplayLabel='廃棄完了'),
    GenCode(tableName='t_use', fieldName='useStatus', fieldValue=0,
            fieldDisplayLabel='未利用'),
    GenCode(tableName='t_use', fieldName='useStatus', fieldValue=1,
            fieldDisplayLabel='利用中'),
    GenCode(tableName='t_use', fieldName='useStatus', fieldValue=2,
            fieldDisplayLabel='利用完了'),
    GenCode(tableName='m_account', fieldName='accountStatus', fieldValue=0,
            fieldDisplayLabel='仮登録'),
    GenCode(tableName='m_account', fieldName='accountStatus', fieldValue=1,
            fieldDisplayLabel='本登録'),
    GenCode(tableName='m_account', fieldName='accountStatus', fieldValue=2,
            fieldDisplayLabel='削除'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=0,
            fieldDisplayLabel='見積依頼'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=1,
            fieldDisplayLabel='回答'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=2,
            fieldDisplayLabel='承認依頼'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=3,
            fieldDisplayLabel='承認'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=4,
            fieldDisplayLabel='入荷予定登録・償却登録'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=5,
            fieldDisplayLabel='発注'),
    GenCode(tableName='t_procurement', fieldName='procurementStatus', fieldValue=6,
            fieldDisplayLabel='入荷済み'),
    GenCode(tableName='t_arrival', fieldName='inspectionStatus', fieldValue=0,
            fieldDisplayLabel='未検品'),
    GenCode(tableName='t_arrival', fieldName='inspectionStatus', fieldValue=1,
            fieldDisplayLabel='合格'),
    GenCode(tableName='t_arrival', fieldName='inspectionStatus', fieldValue=2,
            fieldDisplayLabel='不合格'),
    GenCode(tableName='t_arrival', fieldName='arrivalType', fieldValue=0,
            fieldDisplayLabel='発注'),
    GenCode(tableName='t_arrival', fieldName='arrivalType', fieldValue=1,
            fieldDisplayLabel='持ち込み'),
    GenCode(tableName='t_arrival', fieldName='failureAction', fieldValue=0,
            fieldDisplayLabel='未'),
    GenCode(tableName='t_arrival', fieldName='failureAction', fieldValue=1,
            fieldDisplayLabel='返品(再入荷待ち)'),
    GenCode(tableName='t_arrival', fieldName='failureAction', fieldValue=2,
            fieldDisplayLabel='返品(再入荷なし)'),
    GenCode(tableName='m_item', fieldName='assetType', fieldValue=0,
            fieldDisplayLabel='一般'),
    GenCode(tableName='m_item', fieldName='assetType', fieldValue=1,
            fieldDisplayLabel='ライセンス'),
    GenCode(tableName='t_asset', fieldName='assetType', fieldValue=0,
            fieldDisplayLabel='償却資産(PCセット)'),
    GenCode(tableName='t_asset', fieldName='assetType', fieldValue=1,
            fieldDisplayLabel='償却資産(PC,機器)'),
    GenCode(tableName='t_asset', fieldName='assetType', fieldValue=2,
            fieldDisplayLabel='償却資産(ソフトウェア)'),
    GenCode(tableName='t_asset', fieldName='assetType', fieldValue=3,
            fieldDisplayLabel='消耗品'),
    GenCode(tableName='t_asset', fieldName='assetType', fieldValue=4,
            fieldDisplayLabel='リース'),
    GenCode(tableName='t_asset', fieldName='assetType', fieldValue=5,
            fieldDisplayLabel='レンタル'),
    GenCode(tableName='t_notification_to', fieldName='notificationToType', fieldValue=0,
            fieldDisplayLabel='アカウント'),
    GenCode(tableName='t_notification_to', fieldName='notificationToType', fieldValue=1,
            fieldDisplayLabel='グループ'),
    GenCode(tableName='t_notification_to', fieldName='notificationToType', fieldValue=2,
            fieldDisplayLabel='ベース'),
    GenCode(tableName='m_item_set', fieldName='itemSetType', fieldValue=0,
            fieldDisplayLabel='PCセット'),
    GenCode(tableName='m_asset_set', fieldName='assetSetType', fieldValue=0,
            fieldDisplayLabel='PCセット'),
    GenCode(tableName='t_pick_up', fieldName='pickUpType', fieldValue=0,
            fieldDisplayLabel='集荷待ち（返却）'),
    GenCode(tableName='t_pick_up', fieldName='pickUpType', fieldValue=1,
            fieldDisplayLabel='集荷待ち（修理）'),
)

session.add_all(gen_code)
session.commit()
